version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
    environment:
      - JAVA_OPTS=-Djava.library.path=/DynamoDBLocal_lib -Dsqlite4java.library.path=/DynamoDBLocal_lib

volumes:
  dynamodb_data:
    driver: local
